### ISSUE TITLE
This one

### ISSUE THREAD

**Issue by Guandingyi** [huiyadanli/huiyadanli#13]
![ecioxbbm](https://github.com/huiyadanli/huiyadanli/assets/109437227/ed9f9a01-1f96-4b30-96b0-198718ac7951)

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

![image](https://github.com/huiyadanli/huiyadanli/assets/15783049/9b7044a3-61ef-4635-ab81-d1d52dedc864)
