### ISSUE TITLE
原神地图识别

### ISSUE THREAD

**Issue by DrChang03** [huiyadanli/huiyadanli#18]
您好，我先问一下您们是如何识别原神地图坐标呢?

如果可以的话能不能分享一下，我想试试做一个自动采取神瞳json文件

**Comment by huiyadanli** [comment]
方法很多

我们用的是用SIFT特征匹配识别小地图的位置

https://github.com/babalae/better-genshin-impact/tree/main/BetterGenshinImpact/Core/Recognition/OpenCv/FeatureMatch
