### ISSUE TITLE
QQNT

### ISSUE THREAD

**Issue by TokisakiKuru3** [huiyadanli/huiyadanli#19]
大佬，请问这个什么解决
![F5A61A4CCF497D046BCBC41DCC920842](https://github.com/user-attachments/assets/a54d10ca-f2ba-4135-9421-c6c4e40f6a86)

**Comment by xiaodaidai999** [comment]
我也是这个问题，赶往大佬出个解决教程

**Comment by huiyadanli** [comment]
暂时不支持了，等QQNT稳定一个版本再说吧。。
