### ISSUE TITLE
微信防撤回补丁

### ISSUE THREAD

**Issue by feilaopao** [huiyadanli/huiyadanli#2]
以前撤回可以看到有撤回提示， 比如xxx撤回了一条消息， 但限制新版本里看不到了， 不知道能不能再实现这个功能？

**Comment by huiyadanli** [comment]
暂时没有方法能做到这个了，可以使用老版本（2.8.0.112~3.3.5.15的版本都可以）。

坐等其他大佬研究出新方法了

**Comment by feilaopao** [comment]
找了个3.3.0的装上果然可以用了， 谢谢啦
