### ISSUE TITLE
无法寻找到应用程序

### ISSUE THREAD

**Issue by shangyanye** [huiyadanli/huiyadanli#23]
如题，点安装路径找不到应用点击

**Comment by huiyadanli** [comment]
你在问什么？

**Comment by shangyanye** [comment]
微信/QQ/TIM防撤回  寻找安装路径无法找到搜索到应用程序
![0be835e3-fece-452b-a256-9be15422e0b5](https://github.com/user-attachments/assets/82a2aa72-962e-4413-a7ee-5f5831938ac0)
