### ISSUE TITLE
一点小小的问题

### ISSUE THREAD

**Issue by Link-Neuvillette** [huiyadanli/huiyadanli#24]
您好 请问您能提供下原神七圣召唤-刻晴 雷神 科莱-牌组的分享码吗,很抱歉因为这点事情打扰了

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/2233a3ba-98e4-4688-b3bc-efe3946b39a3)

https://bgi.huiyadan.com/feats/task/tcg.html
