### ISSUE TITLE
微信[3.8.0.33]多开补丁打不上呢

### ISSUE THREAD

**Issue by syhlhfw** [huiyadanli/huiyadanli#4]
微信自动更新了，最新版本3.8.0.33，重新安装补丁了，但是那个多开总是安装不上
![多开微信不行](https://user-images.githubusercontent.com/101862709/201451667-ebeeb508-44a5-44fc-8c70-7eb6a5c6f663.jpg)
![多开微信不行](https://user-images.githubusercontent.com/101862709/201451700-fb626d74-6ad0-44c0-ad82-af651fd62f91.jpg)

**Comment by huiyadanli** [comment]
已经支持了，重新打就行了
