### ISSUE TITLE
微信最新版3.9.2版本防撤回失败

### ISSUE THREAD

**Issue by hm983763907** [huiyadanli/huiyadanli#6]
开发大大好，目前最新版的微信（v3.9.2）使用上有两个问题：
1.防撤回无法正常使用
2.防撤回的消息气泡下没有显示“xxxx 撤回了一条消息”（在3.9.2版本之前可以正常使用防撤回功能时出现的问题）
麻烦开发大大帮忙看看
![image](https://user-images.githubusercontent.com/55736446/224620405-0c8504e5-ec81-4654-9679-4a0e9b72ebfd.png)

**Comment by lvpinpin1** [comment]
确实存在这个问题。显示打上补丁，但实际防撤回失效

**Comment by Billiow** [comment]
v3.9.2.23 版本之前可以正常使用防撤回功能时出现的问题

**Comment by hm983763907** [comment]
好的，了解了，那在插件适配之前，我回倒微信版本，感谢大佬的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyadanli/huiyadanli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huiyadanli/huiyadanli] 微信最新版3.9.2版本防撤回失败 (Issue #6)





 
v3.9.2.23 版本之前可以正常使用防撤回功能时出现的问题

**Comment by hm983763907** [comment]
> v3.9.2.23 什么时候能匹配呢？还有就是前面版本的微信如何安装呢？

3.9.0版本下载地址：https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

**Comment by kidtttt** [comment]
> > v3.9.2.23 什么时候能匹配呢？还有就是前面版本的微信如何安装呢？
> 
> 3.9.0版本下载地址：https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

十分感谢回复，但是这个而地址下载的也已经不是3.9.0了，安装后直接就是3.9.2.23

**Comment by hm983763907** [comment]
> > > v3.9.2.23 什么时候能匹配呢？还有就是前面版本的微信如何安装呢？
> > 
> > 
> > 3.9.0版本下载地址：https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
> 
> 十分感谢回复，但是这个而地址下载的也已经不是3.9.0了，安装后直接就是3.9.2.23

网友备份的
https://www.aliyundrive.com/s/j7X6u9wnn3p
提取码: 39028

**Comment by Mr-SakuraManJi** [comment]
是否能优化一下？撤回自己发出去的消息时，在对方那边显示已经撤回，但是自己这边撤回的消息还是会存在
![1684221793803](https://github.com/huiyadanli/huiyadanli/assets/109659061/7bd40470-0913-4608-b429-aeb428dc791b)
